(refactor): update bin/setup to use functions from shared/funcs.sh and move shared funcs to shared/funcs.sh
Signed-off-by: quophyie <quophyie@yahoo.com>

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,5 +1,27 @@
 #!/usr/bin/env bash
 
+# shared quantal infra functions
+SHARED_FUNCS_DIR="$( cd "$(dirname "$0")"/../shared >/dev/null 2>&1 ; pwd -P )"
+SHARED_FUNCS="${SHARED_FUNCS_DIR}/funcs.sh"
+
+# *** NOTE ****
+# check_quantal_shared_scripts_dir_exists is defined in shared_infra_funcs.sh
+# check_and_exit_if_infra_scripts_root_env_var_not_exist is defined in shared_infra_funcs.sh
+
+# set -e
+# Naive try catch
+{
+ source ${SHARED_FUNCS}
+} ||
+{
+
+ echo "Quantal shared scripts functions directory not found!"
+ echo "Setup failed"
+ # exit 1
+
+}
+
+
 # Updates  ${PROFILE} file (defined above) to source this file
 function update_profile_with_quantal_shared_scripts_dir_env_var() {
 
@@ -34,147 +56,28 @@ function update_profile_with_quantal_shared_scripts_dir_env_var() {
     fi
 }
 
-# Finds a line containing a given string in a file and inserts the given new
-# after the found line
-# Args: $1 = the path to the file to search
-#       $2 = the string to search for in the file
-#       $3 = the string to insert after the found line
-function insert_after # file line newText
-{
 
-  local file="$1" line="$2" newText="$3"
- # echo "inserting '${newText}' after line  "${line}" in file ${file}"
+function print_post_install_message() {
 
-  if grep -q "${line}" "${file}"; then
-    sed -i ".bak" -e "/^$line/a"$'\\\n\\\n'"$newText"$'\n' "$file"
-  else
-      echo -e "\n${newText}" >> ${file}
-  fi
-}
+          local isThisScriptSourcedBeingByProfileFile
+          is_sourced_by_shell_init_profile_config_file isThisScriptSourcedBeingByProfileFile
 
-# Returns the profile file used in the shell
-#   Arg:
-#       $1: The profile file returned from this function. the caller of this function must provide a variable which
-#           be set by this function to the file name of the profile
-#
-get_profile_file() {
-
-    local  __resultvar=$1
-    bashProfile=~/.bash_profile
-    zshProfile=~/.zshrc
-
-    if [[ "${SHELL}" = "/bin/zsh" ]]; then
-
-        profile=${zshProfile}
-
-    elif [[ "${SHELL}" = "/bin/bash" ]]; then
-
-        profile=${bashProfile}
-    fi
-
-    # this is the value that is returned to the caller of this function
-
-    eval $__resultvar="'${profile}'"
-
-}
-
-function get_sub_shell(){
-
-    local  __resultvar=$1
-    local profileShell
-
-    if test -n "$ZSH_VERSION"; then
-      profileShell=zsh
-    elif test -n "$BASH_VERSION"; then
-      profileShell=bash
-    elif test -n "$KSH_VERSION"; then
-      profileShell=ksh
-    elif test -n "$FCEDIT"; then
-      profileShell=ksh
-    elif test -n "$PS3"; then
-      profileShell=unknown
-    else
-      profileShell=sh
-    fi
-
-    # this is the value that is returned to the caller of this function
-
-    eval $__resultvar="'${profileShell}'"
-
-}
-
-# configures the QUANTAL_SHARED_SCRIPTS_DIR environment variables
-function configure_quantal_shared_scripts_dir_env_var() {
-
- echo "configuring variable QUANTAL_SHARED_SCRIPTS_DIR ..."
- if [ -z "${QUANTAL_SHARED_SCRIPTS_DIR}" ]; then
-
-# get the correct absolute full name of the scripts-infra  directory (i.e. the directory containing this script)
-# this makes sure that no matter where this file is sourced from,
-# INFRA_SCRIPTS_ROOT will always be set to the correct absolute directory i.e. the directory containing
-# this file
-
-
-    local source
-    local homeDir=~
-    local shell
-    # Get the shell executing the script
-     local profileFile
-     get_profile_file profileFile
-     get_sub_shell shell
-
-#     if [[  "${profileFile}" = "${homeDir}/.bash_profile" ]]; then
-#         # see https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
-#        # for more info
-#        source="${BASH_SOURCE[0]}"
-#
-#     elif [[ "${profileFile}" = "${homeDir}/.zshrc"  ]]; then
-#         source="$( cd "$(dirname "${funcfiletrace[1]}")">/dev/null 2>&1 ; pwd -P )"
-#     fi
-
- if [[  "${shell}" = "bash" ]]; then
-         # see https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
-        # for more info
-        source="${BASH_SOURCE[0]}"
-
-     elif [[ "${shell}" = "zsh"  ]]; then
-         source="$( cd "$(dirname "${funcfiletrace[1]}")">/dev/null 2>&1 ; pwd -P )"
-     fi
-
-    local isSymLink=false
-
-    # if this file has been symlinked the code in the while loop will resolve until
-    # we the actual directory containing this file is reached
-    while [ -h "$source" ]; do # resolve $SOURCE until the file is no longer a symlink
-      isSymLink=true
-      DIR="$( cd -P "$( dirname "$source" )" >/dev/null 2>&1 && pwd )"
-      source="$(readlink "$source")"
-      [[ $source != /* ]] && source="$DIR/$source" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
-    done
-
-
-#    if [[ ${isSymLink} == "true" ]]; then
-#        INFRA_SCRIPTS_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
-#    else
-#        INFRA_SCRIPTS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-#    fi
-
-    QUANTAL_SHARED_SCRIPTS_DIR="$( cd -P "$( dirname "$source" )"/../ >/dev/null 2>&1 && pwd )"
-
-   echo "successfully configured variable QUANTAL_SHARED_SCRIPTS_DIR as ${QUANTAL_SHARED_SCRIPTS_DIR} "
-
- fi
+          if [[ ${isThisScriptSourcedBeingByProfileFile} = "false" ]]; then
+            local profileFile=
+            get_profile_file profileFile
+            echo "Please source file ${profileFile} to complete environment variable exports i.e. "
+            echo ""
+            echo "*****************************"
+            echo "!!! PLEASE COPY AND RUN COMMAND BELOW TO COMPLETE EXPORTS !!!"
+            echo ""
+            echo "source ${profileFile}"
+          fi
 
 }
 
 configure_quantal_shared_scripts_dir_env_var
 update_profile_with_quantal_shared_scripts_dir_env_var
-PROFILE_FILE=
-get_profile_file PROFILE_FILE
-echo "Please source file ${PROFILE_FILE} to complete environment variable exports i.e. "
-echo ""
-echo "*****************************"
-echo "!!! PLEASE COPY AND RUN COMMAND BELOW TO COMPLETE EXPORTS !!!"
-echo ""
-echo "source ${PROFILE_FILE}"
+print_post_install_message
+
+
 
